x-ej-list-env: &ej-list-env
  FLASK_ENV: development
  SERVER_NAME: ejudge.listener
  SQLALCHEMY_DATABASE_URI: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/informatics
  REDIS_URL: redis://${REDIS_USER}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
  CELERY_BROKER_URL: redis://${REDIS_USER}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0 

services:
  listener:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    image: ejlist:local
    environment: *ej-list-env
    command: flask run --host 0.0.0.0 --port 23456 --no-reload

  celery:
    image: ejlist:local
    environment: *ej-list-env
    command: celery -A celery_worker.celery worker --loglevel=info
